apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salmonn-models-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salmonn-ckpt-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
